apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-bento
  name: my-bento-service
spec:
  selector:
    app: my-bento
  ports:
    - name: http-metrics
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
