apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-bento
  name: my-bento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-bento
  template:
    metadata:
      labels:
        app: my-bento
    spec:
      containers:
      - image: mj703/iris_classifier
        name: my-bento
        ports:
        - name: http-metrics
          containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 875Mi
          limits:
            cpu: 100m
            memory: 900Mi