apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-monitor
  name: ml-monitor-service
spec:
  selector:
    app: ml-monitor
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP