apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamlit-webapp
  name: streamlit-webapp-service
spec:
  selector:
    app: streamlit-webapp
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
