apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  labels:
    release: prometheus
type: Opaque
stringData:
  slack_webhook_url: 'aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWFhYL1hYWC9YWFg='

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: spring-alertmanager-config
  labels:
    release: prometheus
spec:
  route:
    groupBy: ['alertname']
    groupWait: 5s
    groupInterval: 5m
    repeatInterval: 1h
    continue: true
    receiver: 'slack-notification'
    routes:
      - receiver: 'slack-notification'
        continue: true
  receivers:
    - name: 'slack-notification'
      slackConfigs:
        - channel: 'XXXX'
          apiURL:
            name: slack-webhook
            key: slack_webhook_url
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
          text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"