apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-eks
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-image=mj703/iris_classifier
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/my-image.update-strategy: latest
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: app-kustomize
    repoURL: 'https://github.com/mj703/ML-at-scale-EKS.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false